.\" -*- mode: nroff -*-
.\" man/Rps::Midend::Cmd.3pm - man page for midend utility CLI manager
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (c) 2019 Basile Starynkevitch <basile@starynkevitch.net>

.\" View this man page prior to install using the following:
.\"    $ nroff -mdoc man/obj/Rps::Midend::Cmd.3pm | less

.Dd $Mdocdate$
.Os Debian/Ubuntu
.Dt Rps::Midend::Cmd 3pm


.Sh NAME

.Sh SYNOPSIS

.Sh DESCRIPTION

.Sh FILES

.Sh EXIT STATUS

.Sh DIAGNOSTICS

.Sh HISTORY

.Sh AUTHORS
.An Basile Starynkevitch
.Aq basile@starynkevitch.net
.An Abhishek Chakravarti
.Aq chakravarti.avishek@gmail.com
