.Dd $Mdocdate$
.Os VERSION
.Dt REFPERSYS 7 PS1
.
.Sh NAME
.Nm refpersys
.Nd introductory notes for refpersys(1)
.
.Sh AUTHORS
.An Basile Starynkevitch
.Aq Mt basile@starynkevitch.net
with contributions from others.
See the AUTHORS file for the full list of contributors.
.
.Sh LICENSE
Copyright 2019
.An -nosplit
.An Basile Starynkevitch
.Aq Mt basile@starynkevitch.net .
.Pp
This file is part of RefPerSys.
.Pp
RefPerSys is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
.Pp
RefPerSys is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTIBILITY or FITNESS FOR A
PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.Pp
You should have received a copy of the GNU General Public License along with
RefPerSys.
If not, see
.Aq Lk https://www.gnu.org/licenses/> .
