.\" -*- mode: nroff -*-
.\" man/rpsmidend.1 - man page for midend utility
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (c) 2019 Basile Starynkevitch <basile@starynkevitch.net>

.\" View this man page prior to install using the following:
.\"    $ nroff -mdoc man/obj/rpsmidend.1 | less

.Dd $Mdocdate$
.Os Debian/Ubuntu
.Dt RPSMIDEND 1


.Sh NAME

.Sh SYNOPSIS

.Sh DESCRIPTION

.Sh FILES

.Sh EXIT STATUS

.Sh DIAGNOSTICS

.Sh HISTORY

.Sh AUTHORS
.An Basile Starynkevitch
.Aq basile@starynkevitch.net
.An Abhishek Chakravarti
.Aq chakravarti.avishek@gmail.com
