#!/usr/bin/gmake
## SPDX-License-Identifier: GPL-3.0-or-later
## Description:
##      This file is part of the Reflective Persistent System. refpersys.org
##
##      It is its GNUmakefile, for the GNU make automation builder.
##
## Author(s):
##      Basile STARYNKEVITCH, France, <basile@starynkevitch.net>
##      Abhishek Chakravarti <abhishek@taranjali.org>
##      Nimesh Neema <nimeshneema@gmail.com>
##      Abdullah Siddiqui <siddiquiabdullah92@gmail.com>
##
##      © Copyright 2019 - 2025 The Reflective Persistent System Team
##      team@refpersys.org
##
## License:
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>



## tell GNU make to export all variables by default
export

RPS_GIT_ID:= $(shell ./rps-generate-gitid.sh)
RPS_SHORTGIT_ID:= $(shell ./rps-generate-gitid.sh -s)
RPS_MAKE:= $(MAKE)
RPS_BISON := /usr/bin/bison
RPS_HOST := $(shell /bin/hostname -f)
RPS_ARCH := $(shell /bin/uname -m)
RPS_OPERSYS := $(shell /bin/uname -o | /bin/sed 1s/[^a-zA-Z0-9_]/_/g )
RPS_ATSHARP := $(shell printf '@#')
RPS_HOMETMP := $(shell echo '$$HOME/tmp')
# Carburetta is a parser generator on github.com/kingletbv/carburetta
RPS_CARBURETTA := $(shell /usr/bin/which carburetta)

## REFPERSYS_LTO is by convention for link-time optimization flags

#                                                                
.DEFAULT_GOAL: refpersys
.PHONY: all config objects showtests clean distclean gitpush gitpush2 \
        print-plugin-settings indent redump clean-plugins plugins \
        print-gmake-features \
        one-plugin \
        lto-refpersys \
        test00 test01 test01a test01b test01c test01d test01e test01f \
        test02 test03 test03nt test04 \
        test05 test06 test07 test07a \
        test08 test09 test-load \
	testfltk1 testfltk2 testfltk3 testfltk4

SYNC=/bin/sync

## a formatter to restrict width to 75 columns
FMT=/usr/bin/fmt

## a C and C++ indenter and its flags
ASTYLE=/usr/bin/astyle
ASTYLEFLAGS= --verbose --style=gnu  --indent=spaces=2  --convert-tabs

-include _config-refpersys.mk

CFLAGS?= -O -g -Wall $(RPS_LTO)

### Human hand-written C++ sources
REFPERSYS_HUMAN_CPP_SOURCES=$(wildcard *_rps.cc)

### corresponding object files
REFPERSYS_HUMAN_CPP_OBJECTS=$(patsubst %.cc, %.o, $(REFPERSYS_HUMAN_CPP_SOURCES))

### Generated C++ sources which are written at dump time and needs to be git managed
REFPERSYS_GENERATED_CPP_SOURCES := $(wildcard generated/*.cc)

### corresponding object files
REFPERSYS_GENERATED_CPP_OBJECTS=$(patsubst %.cc, %.o, $(REFPERSYS_GENERATED_CPP_SOURCES))

## altredump is dumping into....
RPS_ALTDUMPDIR_PREFIX?= /tmp/refpersys-$(RPS_SHORTGIT_ID)

### required libraries not being known to pkg-config
## unistring is https://www.gnu.org/software/libunistring/
## backtrace is https://github.com/ianlancetaylor/libbacktrace (also inside GCC source)
## libgccjit is from https://gcc.gnu.org/onlinedocs/jit/
## try using GNU lightning is from https://www.gnu.org/software/lightning/ (for machine code generation)
REFPERSYS_NEEDED_LIBRARIES= -llightning -lunistring -lbacktrace -lgmp
## TODO after june 2024, add the libgccjit...

### desired plugins (their basename under plugins_dir/)
### Basile removed _rpsplug_gramrepl in sept. 2024
REFPERSYS_DESIRED_PLUGIN_BASENAMES= \
  rpsplug_createclass \
  rpsplug_createnamedattribute \
  rpsplug_createnamedselector \
  rpsplug_create_cplusplus_primitive_type \
  rpsplug_simpinterp

## perhaps add above in Feb. 2025 a plugin generated by Carburetta? https://carburetta.com/

all:
	@if [ -z "$(REFPERSYS_TOPDIR)" ]; then \
		REFPERSYS_TOPDIR="$(pwd)"; \
		/usr/bin/printf "missing REFPERSYS_TOPDIR, using default\n" > /dev/stderr; \
	fi
	@/usr/bin/printf 'RPS_HOMETMP is %s\n' "$(RPS_HOMETMP)"
	@/usr/bin/printf "make features: %s\n" "$(.FEATURES)" | $(FMT)
	$(MAKE) tools/do-configure-refpersys
	@/usr/bin/printf "hand-written C++ code: %s\n" "$(REFPERSYS_HUMAN_CPP_SOURCES)" | $(FMT)
	@if [ ! -f _config-refpersys.mk ]; then \
	   echo missing _config-refpersys.mk for GNUmakefile > /dev/stderr; \
	   echo run $(MAKE) config > /dev/stderr ; \
	   exit 1 ; \
	fi
	$(MAKE) refpersys
	$(MAKE) do-build-refpersys-plugin
	@/usr/bin/printf "\n\n\nMaking RefPerSys plugins\n\n"
	$(MAKE) plugins

objects: $(REFPERSYS_HUMAN_CPP_OBJECTS) $(REFPERSYS_GENERATED_CPP_OBJECTS)  __timestamp.o

.SECONDARY:  __timestamp.c 
	$(SYNC)

lto-refpersys:
	$(MAKE) clean
	$(RM) __timestamp.o
	$(MAKE) -j3 REFPERSYS_LTO=-flto objects
	$(REFPERSYS_CXX) -flto -rdynamic \
             $(REFPERSYS_COMPILER_FLAGS) \
             $(REFPERSYS_LINKER_FLAGS) \
             -o $@ \
             $(REFPERSYS_HUMAN_CPP_OBJECTS) \
             $(REFPERSYS_GENERATED_CPP_OBJECTS) __timestamp.o \
	      $(shell $(REFPERSYS_CXX) -print-file-name=libbacktrace.a) \
              $(shell $(REFPERSYS_FLTKCONFIG) -g --ldflags) \
              -L/usr/local/lib $(REFPERSYS_NEEDED_LIBRARIES) \
               $(REFPERSYS_LINKER_FLAGS) \
              $(shell pkg-config --libs $(sort $(PACKAGES_LIST))) -ldl

config: tools/do-configure-refpersys do-scan-refpersys-pkgconfig GNUmakefile
	tools/do-configure-refpersys
	$(MAKE) _scanned-pkgconfig.mk


#### the configurator tool
tools/do-configure-refpersys: tools/do-configure-refpersys.c |GNUmakefile rps-generate-gitid.sh
	$(CC) -Wall -Wextra -DRPSCONF_GIT_ID=\"$(shell ./rps-generate-gitid.sh -s)\" \
              -DRPSCONF_OPERSYS=\"$(RPS_OPERSYS)\" \
              -DRPSCONF_ARCH=\"$(RPS_ARCH)\" \
              -DRPSCONF_HOST=\"$(RPS_HOST)\" \
              $(CFLAGS) $^ -o $@ -lgccjit -lreadline -lncurses -ldl
## If GNU readline library is unavailable add
## -DRPSCONF_WITHOUT_READLINE above and remove the -lreadline above.
##
## If GNU ncurses library is unavailable add -DRPSCONF_WITHOUT_NCURSES
## above and remove the -lncurses above.
##
## If libgccjit (see https://gcc.gnu.org/onlinedocs/jit/ ...) is
## unavailable add -DRPSCONF_WITHOUT_GCCJIT

######
do-scan-refpersys-pkgconfig: do-scan-refpersys-pkgconfig.c |GNUmakefile rps-generate-gitid.sh
	$(CC) -Wall -Wextra -DGIT_ID=\"$(shell ./rps-generate-gitid.sh -s)\" \
              $(CFLAGS) $^ -o $@

do-build-refpersys-plugin: do-build-refpersys-plugin.cc __timestamp.c
	$(CXX) -Wall -Wextra  -DGIT_ID=\"$(shell ./rps-generate-gitid.sh -s)\" $(CFLAGS) -g $^ -o $@



clean: clean-plugins
	$(RM) tmp* *~ *.o
	$(RM) do-scan-refpersys-pkgconfig tools/do-configure-refpersys do-build-refpersys-plugin 
	$(RM) refpersys lto-refpersys
	$(RM) *% %~
	$(RM) *.gch
	$(RM) *.orig
	$(RM) */*~ */*% */*.orig
	$(RM) */*.so
	$(RM) *.ii
	$(RM) core*
	$(RM) Make-dependencies/__*


clean-plugins:
	$(RM) -v plugins_dir/*.o
	$(RM) -v plugins_dir/*.so
	$(RM) -v plugins_dir/_*
	$(RM) -v _rpsplug* */_rpsplug*

distclean: clean
	$(RM) build.time  _config-refpersys.mk  _scanned-pkgconfig.mk  __timestamp.*
	$(RM) __*.mkdep Make-dependencies/__*.mkdep
	$(RM) do-scan-refpersys-pkgconfig

-include _scanned-pkgconfig.mk

-include $(wildcard Make-dependencies/__*.mkdep)

_scanned-pkgconfig.mk: $(REFPERSYS_HUMAN_CPP_SOURCES) |GNUmakefile do-scan-refpersys-pkgconfig
	./do-scan-refpersys-pkgconfig refpersys.hh $(REFPERSYS_HUMAN_CPP_SOURCES) > $@

__timestamp.c: rps-generate-timestamp.sh GNUmakefile $(wildcard *.cc *.hh generated/*.cc generated *.hh)
	@echo MAKE is "$(MAKE)" CXX is "$(REFPERSYS_CXX)" GPP is "$(REFPERSYS_GPP)" and "$(GPP)"
	+env "MAKE=$(shell /bin/which gmake)" "CXX=$(REFPERSYS_CXX)" "GPP=$(REFPERSYS_GPP)" "CXXFLAGS=$(REFPERSYS_PREPRO_FLAGS) $(REFPERSYS_COMPILER_FLAGS)" ./rps-generate-timestamp.sh $@ > $@

__timestamp.o: __timestamp.c |GNUmakefile
	$(CC) -fPIC $(RPS_LTO) -c -O -g -Wall -DGIT_ID=\"$(shell ./rps-generate-gitid.sh -s)\" $^ -o $@

#was
#refpersys: $(REFPERSYS_HUMAN_CPP_OBJECTS) \
#               $(REFPERSYS_GENERATED_CPP_OBJECTS) \
#                   __timestamp.c |  GNUmakefile
refpersys: objects |  GNUmakefile
	$(RM) __timestamp.o
	$(MAKE) __timestamp.o
	@if [ -z "$(REFPERSYS_CXX)" ]; then echo should make config ; exit 1; fi
	@echo RefPerSys human C++ source files $(REFPERSYS_HUMAN_CPP_SOURCES)
#       @echo RefPerSys human C++ object files $(REFPERSYS_HUMAN_CPP_OBJECTS)
	@echo RefPerSys generated C++ files $(REFPERSYS_GENERATED_CPP_SOURCES)
#	@echo RefPerSys generated C++ object files $(REFPERSYS_GENERATED_CPP_OBJECTS)
	@echo PACKAGES_LIST is $(PACKAGES_LIST)
	@echo RPS_LTO is $(RPS_LTO)
	@echo FLTKconfig is  $(REFPERSYS_FLTKCONFIG)
	@echo FLTK stuff is  $(shell $(REFPERSYS_FLTKCONFIG) -g --ldflags)
	@echo REFPERSYS_NEEDED_LIBRARIES is $(REFPERSYS_NEEDED_LIBRARIES)
	@echo REFPERSYS_HUMAN_CPP_OBJECTS is $(REFPERSYS_HUMAN_CPP_OBJECTS) | /usr/bin/fmt | /bin/sed '2,$$s/^/ /'
	@echo REFPERSYS_GENERATED_CPP_OBJECTS is $(REFPERSYS_GENERATED_CPP_OBJECTS) | /usr/bin/fmt | /bin/sed '2,$$s/^/ /'
	$(MAKE) RPS_LTO=$(RPS_LTO) $(REFPERSYS_HUMAN_CPP_OBJECTS) $(REFPERSYS_GENERATED_CPP_OBJECTS) __timestamp.o
	@if [ -x $@ ]; then /bin/mv -v --backup $@ $@~ ; fi
	$(REFPERSYS_CXX) $(RPS_LTO) -rdynamic -o $@ \
             $(REFPERSYS_HUMAN_CPP_OBJECTS) \
             $(REFPERSYS_GENERATED_CPP_OBJECTS) \
             __timestamp.o \
	      $(shell $(REFPERSYS_CXX) -print-file-name=libbacktrace.a) \
              $(shell $(REFPERSYS_FLTKCONFIG) -g --ldflags) \
              -L/usr/local/lib $(REFPERSYS_NEEDED_LIBRARIES) \
              $(REFPERSYS_LINKER_FLAGS) \
              $(shell pkg-config --libs $(sort $(PACKAGES_LIST))) -ldl
	@/bin/rm -vf __timestamp.o

%.ii: %.cc | refpersys.hh GNUmakefile

plugins: |GNUmakefile do-build-refpersys-plugin do-scan-refpersys-pkgconfig
	@printf "\n\n making plugins desired basenames=%s\n" "$(REFPERSYS_DESIRED_PLUGIN_BASENAMES)"
	+$(MAKE) $(patsubst %, plugins_dir/%.so, $(REFPERSYS_DESIRED_PLUGIN_BASENAMES))

define RPS_GUILE_SCRIPT
;; Scheme function for GUILE
;; www.gnu.org/software/guile/manual/html_node/
(use-modules (ice-9 textual-ports))
(use-modules (ice-9 format))
(define rpsg-stdout (current-output-port))
(define (rpsguilemk-compile-plugin cppsrc plugobj)
;; temporary guile code
;; cppsrc is the C++ source file of the plugin
;; plugobj is the generated shared object
(format #t "rpsguilemk-compile-plugin cppsrc=~S plugob=~S\n"
               cppsrc plugobj)
)

endef
$(guile $(RPS_GUILE_SCRIPT))

one-plugin: refpersys | GNUmakefile do-build-refpersys-plugin do-scan-refpersys-pkgconfig
	$(guile rpsguilemk-compile-plugin $(REFPERSYS_PLUGIN_SOURCE) $(REFPERSYS_PLUGIN_SHARED_OBJECT))
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $(REFPERSYS_PLUGIN_SOURCE) -o $(REFPERSYS_PLUGIN_SHARED_OBJECT)

plugins_dir/rpsplug_createclass.so:  plugins_dir/rpsplug_createclass.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_cplusplustypes.so:  plugins_dir/rpsplug_cplusplustypes.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_createnamedselector.so:  plugins_dir/rpsplug_createnamedselector.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_createnamedattribute.so:  plugins_dir/rpsplug_createnamedattribute.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_createsymbol.so:  plugins_dir/rpsplug_createsymbol.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@


plugins_dir/rpsplug_create_cplusplus_primitive_type.so:  plugins_dir/rpsplug_create_cplusplus_primitive_type.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_simpinterp.so:  plugins_dir/rpsplug_simpinterp.cc  refpersys.hh  |GNUmakefile refpersys
	@printf "\n\nRefPerSys-gnumake building special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) -fPIC -shared -O1 -g \
             -I generated/ -I .  $(shell pkg-config --cflags jsoncpp) \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $^ -o $@

plugins_dir/rpsplug_simpinterp1.so:  plugins_dir/rpsplug_simpinterp.cc  refpersys.hh  |GNUmakefile refpersys do-build-refpersys-plugin
	@printf "\n\nRefPerSys-gnumake dobuilding special plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	./do-build-refpersys-plugin -v "$<" -o "$@"

plugins_dir/%.so: plugins_dir/%.cc refpersys.hh do-build-refpersys-plugin |GNUmakefile
	@printf "\n\nRefPerSys-gnumake building plugin %s from source %s in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
	@printf "RPS_MAKE is %s and MAKE is %s for refpersys plugin at=%s PATH=%s\n" \ "$(RPS_MAKE)" "$(MAKE)" "$@"  "$$PATH"
#	env PATH=$$PATH $(shell $(RPS_MAKE) -s print-plugin-settings) /usr/bin/printenv
#	env PATH=$$PATH $(shell $(RPS_MAKE) -s print-plugin-settings) ./do-build-refpersys-plugin -v $< -o $@
	/usr/bin/printenv
	./do-build-refpersys-plugin -v $< -o $@


################################# obsolete stuff
#plugins_dir/_rpsplug_gramrepl.yy: plugins_dir/gramrepl_rps.yy.gpp refpersys.hh refpersys |GNUmakefile _config-refpersys.mk  _scanned-pkgconfig.mk
#	@printf "RefPerSys-gnumake building plugin GNU bison code %s from %s using $(REFPERSYS_GPP) in %s\n" "$@"  "$<"  "$$(/bin/pwd)"
#	$(REFPERSYS_GPP) -x -I generated/ -I . \
#            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
#            -DRPS_HOST=$(RPS_HOST) \
#            -DRPS_ARCH=$(RPS_ARCH) \
#            -DRPS_OPERSYS=$(RPS_OPERSYS) \
#            -DRPS_GPP_INPUT="$<"    -DRPS_GPP_OUTPUT="$@"    \
#            -DRPS_GPP_INPUT_BASENAME="$(basename $<)" \
#            -U  '@&'  '&@'  '('  '&,'  ')'  '('  ')' '$(RPS_ATSHARP)'   '\\'  \
#            -o $@ $<
#
#
#plugins_dir/_rpsplug_gramrepl.cc: plugins_dir/_rpsplug_gramrepl.yy
#	$(RPS_BISON) --verbose --no-lines --warnings=all --color=tty \
#                     --language=c++ --debug  --token-table \
#                     --header=plugins_dir/_rpsplug_gramrepl.hh \
#                     --output=$@ \
#                   $<
################################

# Target to facilitate git push to both origin and GitHub mirrors
gitpush:
	@echo RefPerSys git pushing.... ; grep -2 url .git/config
	@git push origin
ifeq ($(shell git remote | grep github), github)
	@git push github
else
	@echo "Add github remote as git@github.com:RefPerSys/RefPerSys.git"
	@printf "using: %s\n" 'git remote add --mirror=push github git@github.com:RefPerSys/RefPerSys.git'
endif
	@printf "\n%s git-pushed commit %s of RefPerSys, branch %s ...\n" \
	        "$$(git config --get user.email)" "$$(./rps-generate-gitid.sh -s)" "$$(git branch | fgrep '*')"
	@git log -1 --format=oneline --abbrev=12 --abbrev-commit -q | head -1
	if [ -x $$HOME/bin/push-refpersys ]; then $$HOME/bin/push-refpersys $(shell /bin/pwd) $(RPS_SHORTGIT_ID); fi
	$(SYNC)

gitpush2:
ifeq ($(RPS_GIT_ORIGIN), )
	git remote add origin https://github.com/RefPerSys/RefPerSys.git
	echo "Added GitHub repository as remote, run make gitpush2 again..."
else
	git push $(RPS_GIT_ORIGIN) master
endif
ifeq ($(RPS_GIT_MIRROR), )
	git remote add mirror https://gitlab.com/bstarynk/refpersys.git
	echo "Added GitLab repository as remote, run make gitpush2 again..."
else
	git push $(RPS_GIT_MIRROR) master
endif
	$(SYNC)

load_rps.o: load_rps.cc refpersys.hh \
            generated/rps-constants.hh  generated/rps-names.hh generated/rps-roots.hh |GNUmakefile
	echo dollar-less-F is $(<F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) $(REFPERSYS_COMPILER_FLAGS) \
               -MD -MFMake-dependencies/__$(basename $(@F)).mkdep \
	       $(shell pkg-config --cflags $(PKGLIST_refpersys)) \
               $(shell pkg-config --cflags $(PKGLIST_$(basename $(<F)))) \
               -DRPS_THIS_SOURCE=\"$<\" -DRPS_GITID=\"$(RPS_GIT_ID)\"  \
               -DRPS_SHORTGITID=\"$(RPS_SHORTGIT_ID)\" \
	       -c -o $@ $<
	$(SYNC)

%_rps.o: %_rps.cc refpersys.hh
	echo dollar-less-F is $(<F)
	echo at-F is $(@F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))	
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) $(REFPERSYS_COMPILER_FLAGS) \
               -MD -MFMake-dependencies/__$(basename $(@F)).mkdep \
	       $(shell pkg-config --cflags $(PKGLIST_refpersys)) \
               $(shell pkg-config --cflags $(PKGLIST_$(basename $(<F)))) \
               -DRPS_THIS_SOURCE=\"$<\" -DRPS_GITID=\"$(RPS_GIT_ID)\"  \
               -DRPS_SHORTGITID=\"$(RPS_SHORTGIT_ID)\" \
	       -c -o $@ $<
	$(SYNC)

%_rps.ii:  %_rps.cc refpersys.hh $(wildcard generated/rps*.hh) | GNUmakefile _config-refpersys.mk
	echo dollar-less-F is $(<F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))
	$(REFPERSYS_CXX) -C -E $(REFPERSYS_PREPRO_FLAGS) $(REFPERSYS_COMPILER_FLAGS) \
               -MD -MFMake-dependencies/__$(basename $(@F)).ii.mkdep \
	       $(shell pkg-config --cflags $(PKGLIST_refpersys)) \
               $(shell pkg-config --cflags $(PKGLIST_$(basename $(<F)))) \
               -DRPS_THIS_SOURCE=\"$<\" -DRPS_GITID=\"$(RPS_GIT_ID)\"  \
               -DRPS_SHORTGITID=\"$(RPS_SHORTGIT_ID)\" \
	       $< | /bin/sed 's:^#://#:g' | $(ASTYLE) $(ASTYLEFLAGS)  > $@

fltk_rps.o: fltk_rps.cc refpersys.hh  $(wildcard generated/rps*.hh) | GNUmakefile _config-refpersys.mk
	echo dollar-less-F is $(<F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))
	$(REFPERSYS_CXX) $(REFPERSYS_PREPRO_FLAGS) \
            $(REFPERSYS_COMPILER_FLAGS) \
               -MD -MFMake-dependencies/__$(basename $(@F)).mkdep \
	       $(shell pkg-config --cflags $(PKGLIST_refpersys)) \
               $(shell pkg-config --cflags $(PKGLIST_$(basename $(<F)))) \
               -DRPS_THIS_SOURCE=\"$<\" -DRPS_GITID=\"$(RPS_GIT_ID)\"  \
               -DRPS_SHORTGITID=\"$(RPS_SHORTGIT_ID)\" \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $(shell $(REFPERSYS_FLTKCONFIG) -g --cflags) \
	       -c -o $@ $<
	$(SYNC)

fltk_rps.ii:  fltk_rps.cc refpersys.hh  $(wildcard generated/rps*.hh) | GNUmakefile _config-refpersys.mk
	echo dollar-less-F is $(<F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))
	$(REFPERSYS_CXX) -C -E $(REFPERSYS_PREPRO_FLAGS) \
            $(REFPERSYS_COMPILER_FLAGS) \
               -MD -MFMake-dependencies/__$(basename $(@F)).ii.mkdep \
	       $(shell pkg-config --cflags $(PKGLIST_refpersys)) \
               $(shell pkg-config --cflags $(PKGLIST_$(basename $(<F)))) \
               -DRPS_THIS_SOURCE=\"$<\" -DRPS_GITID=\"$(RPS_GIT_ID)\"  \
               -DRPS_SHORTGITID=\"$(RPS_SHORTGIT_ID)\" \
            -DRPS_SHORTGIT="$(RPS_SHORTGIT_ID)" \
            -DRPS_HOST=$(RPS_HOST) \
            -DRPS_ARCH=$(RPS_ARCH) \
            -DRPS_OPERSYS=$(RPS_OPERSYS) \
	    $(shell $(REFPERSYS_FLTKCONFIG) -g --cflags) \
	       $< | /bin/sed 's:^#://#:g'| $(ASTYLE) $(ASTYLEFLAGS)  > $@

%.ii.o: %.ii | GNUmakefile  _config-refpersys.mk
	echo dollar-less-F is $(<F)
	echo basename-dollar-less-F is $(basename $(<F))
	echo pkglist-refpersys is $(PKGLIST_refpersys)
	echo pkglist-$(basename $(<F)) is $(PKGLIST_$(basename $(<F)))
	$(REFPERSYS_CXX) -c -std=gnu++17 -g -O $< -o $@

## for plugins, see do-build-refpersys-plugin.cc
print-plugin-settings:
	@printf "RPSPLUGIN_CXX='%s'\n" "$(REFPERSYS_CXX)"
	@printf "RPSPLUGIN_CXXFLAGS='%s'\n" "$(REFPERSYS_PREPRO_FLAGS) $(REFPERSYS_COMPILER_FLAGS) $(shell pkg-config --cflags $(PKGLIST_refpersys))"
	@printf "RPSPLUGIN_LDFLAGS='%s'\n"  "-rdynamic -pthread -L /usr/local/lib -L /usr/lib $(LIBES)"

print-gmake-features:
	@echo $(.FEATURES)

indent:
	$(ASTYLE) $(ASTYLEFLAGS) tools/do-configure-refpersys.c
	$(ASTYLE) $(ASTYLEFLAGS) do-scan-refpersys-pkgconfig.c
	$(ASTYLE) $(ASTYLEFLAGS) refpersys.hh
	$(ASTYLE) $(ASTYLEFLAGS) oid_rps.hh
	$(ASTYLE) $(ASTYLEFLAGS) inline_rps.hh
	for f in $(REFPERSYS_HUMAN_CPP_SOURCES) ; do \
	    $(ASTYLE) $(ASTYLEFLAGS) $$f ; done
	for p in $(patsubst %, plugins_dir/%.cc, $(REFPERSYS_DESIRED_PLUGIN_BASENAMES)) ; do \
	    $(ASTYLE) $(ASTYLEFLAGS) $$p ; done
	$(ASTYLE) $(ASTYLEFLAGS) tools/do-configure-refpersys.c

## redump target
redump: refpersys
	./refpersys --dump=. --batch --run-name=$@
	@if git diff -U1|grep '^[+-] ' | grep -v 'origitid|//: gen' ; then \
	  printf "make redump changed in %s git %s\n" $$(pwd)  $(RPS_SHORTGIT_ID); \
          git diff ; \
        else \
	  git checkout rps_manifest.json ; \
            printf "make redump reached fixpoint in %s git %s\n" $$(pwd) $(RPS_SHORTGIT_ID) ; \
        fi
	$(SYNC)

## alternate redump target
altredump:  ./refpersys
	./refpersys --dump=$(RPS_ALTDUMPDIR_PREFIX)_$$$$ --batch --run-name=$@ 2>&1 | tee  $(RPS_ALTDUMPDIR_PREFIX).$$$$.out
	$(SYNC)

################################################################
#### simple tests; the --run-name should start with test and not use $@ because of showtests target
test00: refpersys
	@printf '\f\n\n\n\n////test00 first *****\n'
	./refpersys  -AREPL  --test-repl-lexer 'show help' -B --run-name=test00.1
	@printf '\f\n\n\n\n////test00 second *****\n'
	./refpersys  -AREPL  --test-repl-lexer 'show RefPerSys_system' -B --run-name=test00.2
	@printf '\f\n\n\n////test00 third *****\n'
	./refpersys  -AREPL  --test-repl-lexer '@show put' -B --run-name=test00.3
	@printf '\f\n\n\n////test00 fourth *****\n'
	./refpersys  -AREPL  --test-repl-lexer 'show (1 + 2)' -B --run-name=test00.4
	@printf '\f\n\n\n////test00 help REPL command (fifth) ****\n'
	./refpersys -AREPL -c help -B --run-name=test00.5
	@printf '\n\n\n////test00 FINISHED¤\n\n'

test01: refpersys
	@echo test01 testing simple show help with a lot of debug
	./refpersys -AREPL -c 'show help' -B --run-name=test01
	@printf '\n\n\n////test01 FINISHED¤\n'

test01a:  refpersys
	@echo test01a testing simple show class with a lot of debug
	./refpersys -AREPL -c 'show class' -B --run-name=test01a

	@printf '\n\n\n////test01 FINISHED¤\n'
test01b: refpersys
	./refpersys -AREPL,LOW_REPL  -c 'show help' -B --run-name=test01b
	@printf '\n\n\n////test01b FINISHED¤\n'

test01c: refpersys
	@printf '\n\n\n//+ test01c !parse_sum 1 + 2\n'
	./refpersys -AREPL,LOW_REPL  -c '!parse_sum 1 + 2' -B --run-name=test01c
	@printf '\n\n\n////test01c FINISHED¤\n'

test01d: refpersys
	@printf '\n\n\n//+ test01d !parse_sum 1 + 2 + 3\n'
	./refpersys -AREPL,LOW_REPL  -c '!parse_sum 1 + 2 + 3' -B --run-name=test01d
	@printf '\n\n\n////test01d FINISHED¤\n'

test01e: refpersys
	@printf '\n\n\n//+ test01e !parse_sum 1 + 2 * 3\n'
	./refpersys -AREPL,LOW_REPL  -c '!parse_sum 1 + 2 * 3' -B --run-name=test01e
	@printf '\n\n\n////test01e FINISHED¤\n'

### notice the space after the 3 below
test01f: refpersys
	./refpersys -AREPL,LOW_REPL  -c '!parse_primary 3 ' -B --run-name=test01f
	@printf '\n\n\n////test01f FINISHED¤\n'


test02: refpersys
	./refpersys -AREPL  -c 'show RefPerSys_system' -B --run-name=test02
	@printf '\n\n\n////test02 FINISHED¤\n'

test03: refpersys
	./refpersys -AREPL  -c 'show 1 + 2' -B --run-name=test03
	@printf '\n\n\n////test03 FINISHED¤\n'

## test03 no tty
test03nt: refpersys
	./refpersys --no-terminal -AREPL  -c 'show 1 + 2' -B --run-name=test03nt
	@printf '\n\n\n////test03nt FINISHED¤\n'

test03bis: refpersys
	./refpersys -AREPL  -c 'show 1 + 2 + 3' -B --run-name=test03bis
	@printf '\n\n\n////test03bis FINISHED¤\n'

test04: refpersys
	./refpersys -AREPL  -c 'show  1 * 2 + 3 * 4' -B --run-name=test04
	@printf '\n\n\n////test04 FINISHED¤\n'

test05: refpersys
	./refpersys -AREPL  -c 'show (1 + 2) ' -B --run-name=test05
	@printf '\n\n\n////test05 FINISHED¤\n'

test06: refpersys
	./refpersys -AREPL  -c 'show 1' -B --run-name=test06
	@printf '\n\n\n////test06 FINISHED¤\n'

test07: refpersys
	./refpersys -AREPL -B -c '!parse_term 1' --run-name=test07.1
	./refpersys -AREPL -B -c '!parse_sum 1 + 2' --run-name=test07.2
	@printf '\n\n\n////test07 FINISHED¤\n'

test07a: refpersys
	./refpersys -AREPL -B -c '!parse_term 1' --run-name=$@
	@printf '\n\n\n////test07a FINISHED¤\n'

test08: refpersys
	@echo missing test08 ; exit 1

test09: refpersys
	@echo missing test09 ; exit 1

test10: refpersys 
	./refpersys -AREPL --run-name=test10 --run-delay=6s
	@printf '\n\n\n////test10 FINISHED¤\n'
test-load: refpersys
	./refpersys --batch --run-name=test-load
	@printf '\n\n\n////test-load FINISHED¤\n'

## testing the FLTK graphical interface
testfltk1: refpersys
	@printf '%s git %s\n' $@ $(RPS_SHORTGIT_ID)
	./refpersys -AREPL --run-name=$@ --run-delay=29s  \
                    --fltk=$$HOME/fltk1-refpersys-pref \
                    --pid-file=$(RPS_HOMETMP)/refpersys.pid
	@printf '\n\n\n////testfltk1 FINISHED git %s¤\n' $(RPS_SHORTGIT_ID)

testfltk2: refpersys
	@printf '%s git %s\n' $@ $(RPS_SHORTGIT_ID)
	./refpersys -dPROGARG -AREPL --run-delay=14s --fltk -bg ivory \
                    --run-name=$@ --pid-file=$(RPS_HOMETMP)/refpersys.pid
	@printf '\n\n\n////testfltk2 FINISHED git %s¤\n' $(RPS_SHORTGIT_ID)

testfltk3: refpersys
	@printf '%s git %s\n' $@ $(RPS_SHORTGIT_ID)
	./refpersys -dPROGARG -AREPL --run-name=$@ --run-delay=29s  --fltk -bg lightpink --pid-file=$(RPS_HOMETMP)/refpersys.pid
	@printf '\n\n\n////testfltk3 FINISHED git %s¤\n' $(RPS_SHORTGIT_ID)

testfltk4: refpersys
	@printf '%s git %s\n' $@ $(RPS_SHORTGIT_ID)
	./refpersys -dPROGARG -AREPL --run-name=$@ --run-delay=15m  --fltk -bg peachpuff --echo="hello from $@"
	@printf '\n\n\n////testfltk4 FINISHED git %s¤\n' $(RPS_SHORTGIT_ID)

########### show the testing commands
showtests:
	@printf '\nRefPerSys has %d testing commands\n' $(shell /bin/grep 'run-name=test' GNUmakefile | /bin/grep -v '@' | /bin/wc -l)
	@/bin/grep 'run-name=test' GNUmakefile | /bin/grep -v '@' | /bin/tr -d '\t'
	@printf 'showtests¤ done git %s in %s\n\n' $(RPS_SHORTGIT_ID) $(shell /bin/pwd)
## eof GNUmakefile

