/****************************************************************
 * file gui_qrps.cc
 *
 * Description:
 *      This file is part of the Reflective Persistent System.
 *
 *      It has the Qt5 Graphical User Interface code.
 *
 * Author(s):
 *      Basile Starynkevitch <basile@starynkevitch.net>
 *      Abhishek Chakravarti <abhishek@taranjali.org>
 *      Nimesh Neema <nimeshneema@gmail.com>
 *
 *      © Copyright 2019 The Reflective Persistent System Team
 *      team@refpersys.org
 *
 * License:
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

#include "refpersys.hh"
#include "qtgui_qrps.hh"


////////////////////////////////////////////////// RpsApplication

RpsApplication::RpsApplication(int &argc, char **argv)
{
} // end RpsApplication::RpsApplication

RpsApplication::~RpsApplication()
{
} // end RpsApplication::~RpsApplication


////////////////////////////////////////////////// RpsWindow
RpsWindow::RpsWindow() {
} // end RpsWindow::RpsWindow

RpsWindow::~RpsWindow() {
} // end RpsWindow::~RpsWindow


///////////////////////////////////////////////// generated by moc
#include "_qtgui_qrps.moc.hh"
/************* end  of file gui_qrps.cc ************/
