#! /bin/sh
# -*- mode: sh -*-
# sbin/rpsprovision - provisioning script
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2019 Basile Starynkevitch <basile@starynkevitch.net>


#
# Install Perl dependencies (Debian/Ubuntu only)
#

apt install libgetopt-long-descriptive-perl;
apt install libsmart-comments-perl;
