#!/bin/sh
################################################################################
# file tools/provision
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Description:
#      This file is part of the Reflective Persistent System.
#
#      It provisions a Debian 11 virtual machine through Vagrant on which to
#      build the RefPerSys binary.
#
# Author(s):
#      Basile Starynkevitch <basile@starynkevitch.net>
#      Abhishek Chakravarti <abhishek@taranjali.org>
#      Nimesh Neema <nimeshneema@gmail.com>
#
#      © Copyright 2020 The Reflective Persistent System Team
#      team@refpersys.org & http://refpersys.org/
#
# License:
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
################################################################################


. "$(dirname "0")/msg.sh"


# Writes the Vagrantfile for a generic/debian11 box
write_debian_vgfile()
{
	msg_info 'writing Vagrantfile for Debian 11'

	{
		echo 'Vagrant.configure("2") do |config|';
		echo '  config.vm.box = "generic/debian11"';
		echo '  config.vm.define = "refpersys_debian11";
		echo '  config.ssh.forward_agent = true';
		echo '  config.vm.provision "shell", inline: <<-SHELL';
		echo '    apt update && apt upgrade -y';
		echo '  SHELL';
		echo 'end';
	} > Vagrantfile

	msg_ok 'Vagrantfile written for Debian 11'
}
